name: Angular 12 Build
on:
  push:
    branches:
      - main
      - actions-pipeline
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'

    - name: Install Angular CLI
      run: npm install -g @angular/cli

    - name: Interpolate environment variables
      shell: bash
      id: interpolate
      run: |
         pwd
         ls -la
         cd Backend
         ls -la

    - name: Install Dependencies
      run: npm install

    - name: Build
      run: npm run build 

    - name: Archive Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist
